import type { TaskCollection } from '../../task.types';

import { PHONETICS_TASKS } from './01-phonetics';
import { NOUNS_TASKS } from './02-nouns';
import { CASES_TASKS } from './03-cases';
import { PRONOUNS_TASKS } from './04-pronouns';
import { VERBS_TASKS } from './05-verbs';
import { TENSES_TASKS, SENTENCE_STRUCTURE_TASKS, NEGATION_TASKS } from './06-tenses';
import { ADJECTIVES_TASKS, PREPOSITIONS_TASKS } from './07-adjectives-preps';
import {
  ADVERBS_TASKS,
  NUMBERS_TIME_TASKS,
  CONJUNCTIONS_TASKS,
  IMPERATIVE_TASKS,
  QUESTION_WORDS_TASKS,
  COMMON_PATTERNS_TASKS,
  TIME_EXPRESSIONS_TASKS,
  INFINITIVE_CONSTRUCTIONS_TASKS,
  EVERYDAY_GRAMMAR_TASKS,
  COMMON_CONSTRUCTIONS_TASKS,
} from './08-remaining';

export const A1_TASK_COLLECTIONS: TaskCollection[] = [
  PHONETICS_TASKS,
  NOUNS_TASKS,
  CASES_TASKS,
  PRONOUNS_TASKS,
  VERBS_TASKS,
  TENSES_TASKS,
  SENTENCE_STRUCTURE_TASKS,
  NEGATION_TASKS,
  PREPOSITIONS_TASKS,
  ADVERBS_TASKS,
  NUMBERS_TIME_TASKS,
  CONJUNCTIONS_TASKS,
  ADJECTIVES_TASKS,
  IMPERATIVE_TASKS,
  QUESTION_WORDS_TASKS,
  COMMON_PATTERNS_TASKS,
  TIME_EXPRESSIONS_TASKS,
  INFINITIVE_CONSTRUCTIONS_TASKS,
  EVERYDAY_GRAMMAR_TASKS,
  COMMON_CONSTRUCTIONS_TASKS,
].sort((a, b) => a.order - b.order);